const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com","guerrillamail.com","guerrillamail.net","guerrillamail.org",
  "guerrillamail.biz","guerrillamail.de","guerrillamail.info","tempmail.com",
  "temp-mail.org","temp-mail.io","throwam.com","throwam.net","trashmail.com",
  "trashmail.at","trashmail.io","trashmail.me","trashmail.net","trashmail.org",
  "yopmail.com","yopmail.fr","cool.fr.nf","jetable.fr.nf","nospam.ze.tc",
  "nomail.xl.cx","mega.zik.dj","speed.1s.fr","courriel.fr.nf","moncourrier.fr.nf",
  "monemail.fr.nf","monmail.fr.nf","10minutemail.com","10minutemail.net",
  "10minutemail.org","10minutemail.de","10minutemail.nl","10minutemail.ru",
  "10minutemail.be","10minutemail.co.uk","10minutemail.co.za","sharklasers.com",
  "guerrillamailblock.com","grr.la","guerrillamail.info","spam4.me","spamgourmet.com",
  "spamgourmet.net","spamgourmet.org","spamgourmet.com","spamex.com","spamoff.de",
  "spamthis.co.uk","spaml.de","spam.la","maildrop.cc","mailnull.com","mailnull.net",
  "mailnull.org","mailnesia.com","mailnull.com","mailbait.info","emailondeck.com",
  "dispostable.com","discard.email","discardmail.com","discardmail.de","spam.su",
  "spamfree24.org","spamfree24.de","spamfree24.net","spamfree24.eu","spamfree.eu",
  "spaml.com","fakermail.com","fakemail.net","fakedemail.com","fakeinbox.com",
  "fakeinbox.net","fakeinbox.org","mailme.lv","mailme.gq","mailme7.com",
  "mailmetrash.com","mailin8r.com","mailinator2.com","mailinator3.com",
  "mailinator4.com","mailinator5.com","mailinator6.com","mailinator7.com",
  "mailinator8.com","mailinator9.com","mailinator0.com","safetymail.info",
  "sogetthis.com","spamgrap.de","throwam.com","trashdevil.com","trashdevil.de",
  "trashemail.de","trashmail.at","trashmail.io","trashmail.me","trashmail.net",
  "trashmail.org","trashmail.xyz","wegwerfmail.de","wegwerfmail.net","wegwerfmail.org",
  "wh4f.org","whyspam.me","willhackforfood.biz","willselfdestruct.com",
  "wralmail.com","xagloo.com","xemaps.com","xents.com","xmaily.com","xoxy.net",
  "yapped.net","yeah.net","yogamaven.com","yopmail.com","yopmail.fr","ypmail.webarnak.fr.eu.org",
  "z1p.biz","zehnminuten.de","zehnminuMail.com","zippymail.info","zoemail.org",
  "zomg.info","binkmail.com","bobmail.info","bodhi.lawlita.com","bofthew.com",
  "breakthru.com","brefmail.com","bsnow.net","bspamfree.org","bugmenot.com",
  "bumpymail.com","casualdx.com","caze.be","ce.mintemail.com","chacuo.net",
  "chong-mail.net","civx.org","classified-ads.bid","cust.in","cuvox.de",
  "dacoolest.com","daemsteam.com","dayrep.com","deadaddress.com","deadfake.com",
  "deagot.com","dealja.com","dingbone.com","disposableaddress.com","disposemail.com",
  "dispostable.com","dittoditto.com","dodgeit.com","dodgemail.de","dodsi.com",
  "domozmail.com","dontreg.com","dontsendmespam.de","drdrb.com","drdrb.net",
  "dropmail.me","duam.net","dumpandfuck.com","dumpmail.de","dumpyemail.com",
  "e4ward.com","email-fake.com","emailaaa.com","emailage.cf","emaildienst.de",
  "emailfake.com","emailfake.ml","emailgo.de","emailías.com","emailinfive.com",
  "emailisvalid.com","emailmiser.com","emailo.pro","emailportal.info","emailproxsy.com",
  "emailresort.com","emailsensei.com","emailsingularity.com","emailtemporanea.com",
  "emailtemporanea.net","emailtemporar.ro","emailtemporary.com","emailthe.net",
  "emailtmp.com","emailwarden.com","emailx.at.hm","emailxfer.com","emailz.cf",
  "emailz.ga","emailz.gq","emailz.ml","ephemail.net","etranquil.com",
  "explodemail.com","express.net.ua","extremail.ru","eyepaste.com","ezcxvzbnm.com",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return true;
  return DISPOSABLE_DOMAINS.has(domain);
}
