export const DEFAULT_THEMES = [
  {
    name: "Indigo Pro",
    botName: "Assistant",
    botSubtitle: "We reply in minutes",
    botAvatarEmoji: "⚡",
    primaryColor: "#6366f1",
    headerBgColor: "#6366f1",
    headerTextColor: "#ffffff",
    chatBgColor: "#f9fafb",
    borderRadius: "xl",
    botBubbleBg: "#f3f4f6",
    botBubbleText: "#111827",
    userBubbleBg: "#6366f1",
    userBubbleText: "#ffffff",
    launcherBgColor: "#6366f1",
    launcherIconEmoji: "💬",
    sendButtonColor: "#6366f1",
    inputPlaceholder: "Type a message…",
    showTimestamps: false,
    showPoweredBy: true,
    allowAttachments: false,
    showHelpCenter: false,
    launcherPosition: "bottom-right",
    homeGreeting: "How can we help?",
    homeSubgreeting: "We usually reply in a few minutes.",
    helpCenterTitle: "Help & Resources",
    fontSize: "14px",
    quickReplies: [],
    conversationStarters: [],
    helpArticles: [],
  },
  {
    name: "Emerald Fresh",
    botName: "Support",
    botSubtitle: "Always here to help",
    botAvatarEmoji: "🌿",
    primaryColor: "#10b981",
    headerBgColor: "#10b981",
    headerTextColor: "#ffffff",
    chatBgColor: "#f0fdf4",
    borderRadius: "2xl",
    botBubbleBg: "#d1fae5",
    botBubbleText: "#064e3b",
    userBubbleBg: "#10b981",
    userBubbleText: "#ffffff",
    launcherBgColor: "#10b981",
    launcherIconEmoji: "💬",
    sendButtonColor: "#10b981",
    inputPlaceholder: "Ask us anything…",
    showTimestamps: false,
    showPoweredBy: true,
    allowAttachments: false,
    showHelpCenter: false,
    launcherPosition: "bottom-right",
    homeGreeting: "Hi there! 👋",
    homeSubgreeting: "How can we assist you today?",
    helpCenterTitle: "Help Center",
    fontSize: "14px",
    quickReplies: [],
    conversationStarters: [],
    helpArticles: [],
  },
  {
    name: "Midnight Dark",
    botName: "AI Agent",
    botSubtitle: "Powered by AI",
    botAvatarEmoji: "🤖",
    primaryColor: "#8b5cf6",
    headerBgColor: "#0f172a",
    headerTextColor: "#e2e8f0",
    chatBgColor: "#1e293b",
    borderRadius: "lg",
    botBubbleBg: "#334155",
    botBubbleText: "#e2e8f0",
    userBubbleBg: "#8b5cf6",
    userBubbleText: "#ffffff",
    launcherBgColor: "#8b5cf6",
    launcherIconEmoji: "✨",
    sendButtonColor: "#8b5cf6",
    inputPlaceholder: "Message…",
    showTimestamps: true,
    showPoweredBy: true,
    allowAttachments: false,
    showHelpCenter: false,
    launcherPosition: "bottom-right",
    homeGreeting: "Welcome back 👋",
    homeSubgreeting: "Ask me anything — I'm here 24/7.",
    helpCenterTitle: "Resources",
    fontSize: "14px",
    quickReplies: [],
    conversationStarters: [],
    helpArticles: [],
  },
  {
    name: "Rose Boutique",
    botName: "Concierge",
    botSubtitle: "Premium support",
    botAvatarEmoji: "🌸",
    primaryColor: "#f43f5e",
    headerBgColor: "#f43f5e",
    headerTextColor: "#ffffff",
    chatBgColor: "#fff1f2",
    borderRadius: "2xl",
    botBubbleBg: "#ffe4e6",
    botBubbleText: "#881337",
    userBubbleBg: "#f43f5e",
    userBubbleText: "#ffffff",
    launcherBgColor: "#f43f5e",
    launcherIconEmoji: "💬",
    sendButtonColor: "#f43f5e",
    inputPlaceholder: "How can we help you?",
    showTimestamps: false,
    showPoweredBy: true,
    allowAttachments: false,
    showHelpCenter: false,
    launcherPosition: "bottom-right",
    homeGreeting: "Welcome! 🌸",
    homeSubgreeting: "Our team is ready to assist you.",
    helpCenterTitle: "Support Center",
    fontSize: "14px",
    quickReplies: [],
    conversationStarters: [],
    helpArticles: [],
  },
  {
    name: "Ocean Blue",
    botName: "Helper",
    botSubtitle: "Fast & friendly",
    botAvatarEmoji: "🐬",
    primaryColor: "#0ea5e9",
    headerBgColor: "#0ea5e9",
    headerTextColor: "#ffffff",
    chatBgColor: "#f0f9ff",
    borderRadius: "xl",
    botBubbleBg: "#e0f2fe",
    botBubbleText: "#0c4a6e",
    userBubbleBg: "#0ea5e9",
    userBubbleText: "#ffffff",
    launcherBgColor: "#0ea5e9",
    launcherIconEmoji: "💬",
    sendButtonColor: "#0ea5e9",
    inputPlaceholder: "Type your question…",
    showTimestamps: false,
    showPoweredBy: true,
    allowAttachments: false,
    showHelpCenter: false,
    launcherPosition: "bottom-right",
    homeGreeting: "Hey! How can we help? 🌊",
    homeSubgreeting: "We reply fast — usually under a minute.",
    helpCenterTitle: "Help & Docs",
    fontSize: "14px",
    quickReplies: [],
    conversationStarters: [],
    helpArticles: [],
  },
] as const;
